In [2]:
import numpy as np
import pandas as pd
import seaborn as sb
import matplotlib.pyplot as plt
import sklearn

from pandas import Series, DataFrame
from pylab import rcParams
from sklearn import preprocessing
from sklearn.linear_model import LogisticRegression
from sklearn.cross_validation import train_test_split
from sklearn import metrics 
from sklearn.metrics import classification_report
from sklearn.preprocessing import scale
from sklearn.decomposition import PCA

In [6]:
import os
dir=os.getcwd()
dir

'C:\\Users\\LENOVO\\Desktop\\Machine learning\\PYTHON\\lynda'

In [7]:
data=pd.read_csv("b5.csv")

In [9]:
data.columns

Index([u'E1', u'E2', u'E3', u'E4', u'E5', u'E6', u'E7', u'E8', u'E9', u'E10',
       u'N1', u'N2', u'N3', u'N4', u'N5', u'N6', u'N7', u'N8', u'N9', u'N10',
       u'A1', u'A2', u'A3', u'A4', u'A5', u'A6', u'A7', u'A8', u'A9', u'A10',
       u'C1', u'C2', u'C3', u'C4', u'C5', u'C6', u'C7', u'C8', u'C9', u'C10',
       u'O1', u'O2', u'O3', u'O4', u'O5', u'O6', u'O7', u'O8', u'O9', u'O10'],
      dtype='object')

In [10]:
data.head()

E1  E2  E3  E4  E5  E6  E7  E8  E9  E10 ...   O1  O2  O3  O4  O5  O6  O7  \
0   4   2   5   2   5   1   4   3   5    1 ...    4   1   3   1   5   1   4   
1   2   2   3   3   3   3   1   5   1    5 ...    3   3   3   3   2   3   3   
2   5   1   1   4   5   1   1   5   5    1 ...    4   5   5   1   5   1   5   
3   2   5   2   4   3   4   3   4   4    5 ...    4   3   5   2   4   2   5   
4   3   1   3   3   3   1   3   1   3    5 ...    3   1   1   1   3   1   3   

   O8  O9  O10  
0   2   5    5  
1   1   3    2  
2   5   5    5  
3   2   5    5  
4   1   5    3  

[5 rows x 50 columns]

In [12]:
data["E1"].value_counts()

3    5263
1    4463
2    4340
4    3459
5    1405
Name: E1, dtype: int64

In [16]:
X=data.values
X

array([[4, 2, 5, ..., 2, 5, 5],
       [2, 2, 3, ..., 1, 3, 2],
       [5, 1, 1, ..., 5, 5, 5],
       ..., 
       [2, 5, 4, ..., 5, 5, 5],
       [1, 4, 2, ..., 3, 5, 5],
       [2, 3, 1, ..., 5, 5, 5]], dtype=int64)

In [18]:
scaled=scale(X)
scaled

array([[ 1.112632  , -0.57855181,  1.28086553, ..., -0.96448433,
         0.88177594,  1.0099427 ],
       [-0.51209309, -0.57855181, -0.33817724, ..., -1.76030372,
        -1.15794039, -2.03840414],
       [ 1.92499454, -1.34069418, -1.95722   , ...,  1.42297383,
         0.88177594,  1.0099427 ],
       ..., 
       [-0.51209309,  1.70787529,  0.47134415, ...,  1.42297383,
         0.88177594,  1.0099427 ],
       [-1.32445564,  0.94573292, -1.14769862, ..., -0.16866494,
         0.88177594,  1.0099427 ],
       [-0.51209309,  0.18359055, -1.95722   , ...,  1.42297383,
         0.88177594,  1.0099427 ]])

In [20]:
pca=PCA()
pca.fit(scaled)
print (pca.explained_variance_ratio_)

[ 0.16101911  0.09246263  0.07527279  0.07100381  0.05526279  0.0313044
  0.02660753  0.02099101  0.01937029  0.01849593  0.01794133  0.01735232
  0.01689316  0.01604282  0.01576013  0.01470117  0.01459846  0.01438242
  0.01362569  0.01322527  0.0131285   0.01268631  0.01223362  0.01180048
  0.01164071  0.01136677  0.01108761  0.0106515   0.01045028  0.0102118
  0.01003675  0.00983507  0.00974897  0.00963948  0.0089566   0.00894
  0.00868373  0.00840808  0.00831106  0.00808253  0.00793945  0.00760062
  0.00748126  0.00727417  0.00694749  0.00689884  0.00650197  0.00647554
  0.0062404   0.00442735]


In [21]:
pca=PCA(n_components=5)
pca.fit(scaled)
print (pca.explained_variance_ratio_)

[ 0.16101911  0.09246262  0.07527278  0.07100347  0.05526177]
